name: CI

on:
  workflow_dispatch:
  push:
    branches:
      - readme
    paths:
      - .github/workflows/ci.yml

env:
  SCRIPT_REPO: ${{ github.repository }}
  SCRIPT_REF: ${{ github.ref_name }}
  UBOOT_REPO: qxar86/onecloud-u-boot
  UBOOT_RELEASE: latest
  UBOOT_BURNIMG: eMMC.burn.img
  ARMBIAN_REPO: armbian/build
  ARMBIAN_REF: main
  PATCHES: 4077,5076
  PATCHES_DISABLED: 5082

permissions:
  contents: write

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-22.04
    outputs:
      env: ${{ steps.get.outputs.env }}
    steps:
      - id: get
        name: Get repositories information
        run: |
          TIME="$(curl -s https://api.github.com/repos/${SCRIPT_REPO}/actions/runs/${GITHUB_RUN_ID} | jq -r .created_at)"
          TAG="ci-$(date -d "${TIME}" -u +'%Y%m%d-%H%M%S-%Z')"

          SCRIPT_SHA=$(curl -s https://api.github.com/repos/${SCRIPT_REPO}/commits/${SCRIPT_REF} | jq -r .sha)
          UBOOT_TAG=$(curl -s https://api.github.com/repos/${UBOOT_REPO}/releases/${UBOOT_RELEASE} | jq -r .tag_name)
          ARMBIAN_SHA=$(curl -s https://api.github.com/repos/${ARMBIAN_REPO}/commits/${ARMBIAN_REF} | jq -r .sha)

          cat <<EOF | sed -E 's/^  //' >>$GITHUB_ENV
            TIME=$TIME
            TAG=$TAG
            SCRIPT_SHA=$SCRIPT_SHA
            UBOOT_TAG=$UBOOT_TAG
            ARMBIAN_SHA=$ARMBIAN_SHA
          EOF
          echo "env=$(cat $GITHUB_ENV | base64 -w 0)" >>$GITHUB_OUTPUT

      - name: Generate release informations
        run: |
          cat <<EOF | sed -E 's/^  //' | tee Release.md
            CI $(date -d "$TIME" +'%Y-%m-%d %H:%M:%S %Z(%:z)')

            # Sources
            Script: [${SCRIPT_REPO}@${SCRIPT_REF}](https://github.com/${SCRIPT_REPO}/tree/${SCRIPT_REF}) ([\`${SCRIPT_SHA}\`](https://github.com/${SCRIPT_REPO}/tree/${SCRIPT_SHA}))
            U-Boot: [${UBOOT_REPO}@${UBOOT_RELEASE}](https://github.com/${UBOOT_REPO}/releases/tag/${UBOOT_RELEASE}) ([\`${UBOOT_TAG}\`](https://github.com/${UBOOT_REPO}/releases/tag/${UBOOT_TAG}))
            Armbian: [${ARMBIAN_REPO}@${ARMBIAN_REF}](https://github.com/${ARMBIAN_REPO}/tree/${ARMBIAN_REF}) ([\`${ARMBIAN_SHA}\`](https://github.com/${ARMBIAN_REPO}/tree/${ARMBIAN_SHA}))

            ${PATCHES:+$(
              echo "# Patches"
              echo "${PATCHES}" | tr ',' '\n' | sed -E 's|(.*)|[armbian/build#\1](http://github.com/armbian/build/pull/\1)|'
            )}

            # SHA256
          EOF
          echo "NAME=$(head --line=1 Release.md)" >>$GITHUB_ENV
          tail --line=+2 Release.md >Body.md

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          target_commitish: ${{ github.sha }}
          name: ${{ env.NAME }}
          body_path: Body.md

  build-debs:
    name: Build Kernel Debs
    needs: prepare
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        BRANCH: [current]
    steps:
      - name: Import env
        run: echo "$(echo "${{ needs.prepare.outputs.env }}" | base64 -d)" >>$GITHUB_ENV

      - name: Checkout Armbian
        uses: actions/checkout@v4
        with:
          repository: ${{ env.ARMBIAN_REPO }}
          ref: ${{ env.ARMBIAN_SHA }}

      - name: Apply Patches
        if: ${{ env.PATCHES }}
        run: |
          curl -L -O "https://github.com/armbian/build/pull/{${PATCHES}}.patch"
          for file in *.patch; do
            patch --batch -p1 -N <"$file" || true
          done

      - name: Build Kernel
        run: |
          export GITHUB_ACTIONS=false
          sudo --preserve-env ./compile.sh kernel ALLOW_ROOT=yes BOARD=onecloud BRANCH=${{ matrix.BRANCH }} EXPERT=yes USE_CCACHE=no
          sudo chown $(id -u):$(id -g) -R output/

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: output/debs/*.deb

  build:
    name: Build ${{ matrix.RELEASE }}-${{ matrix.TYPE }}
    needs: [ prepare, build-debs ]
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        BRANCH: [current]
        RELEASE:
          - jammy    # Ubuntu 22.04
          - noble    # Ubuntu 24.04
          - bookworm # Debian 12
          - trixie   # Debian 13
        TYPE:
          - minimal
          - cli
    steps:
      - name: Import env
        run: echo "$(echo "${{ needs.prepare.outputs.env }}" | base64 -d)" >>$GITHUB_ENV

      - name: Checkout Armbian
        uses: actions/checkout@v4
        with:
          repository: ${{ env.ARMBIAN_REPO }}
          ref: ${{ env.ARMBIAN_SHA }}

      - name: Download Kernel Debs
        uses: actions/download-artifact@v4
        with:
          name: debs-${{ matrix.BRANCH }}
          path: output/debs/

      - name: Build OS Image
        run: |
          export GITHUB_ACTIONS=false
          sudo --preserve-env ./compile.sh build \
              ALLOW_ROOT=yes BOARD=onecloud BRANCH=${{ matrix.BRANCH }} RELEASE=${{ matrix.RELEASE }} \
              KERNEL_CONFIGURE=no EXPERT=yes SKIP_EXTERNAL_TOOLCHAINS=yes USE_CCACHE=no \
              BUILD_MINIMAL=${{ matrix.TYPE == 'minimal' && 'yes' || 'no' }} \
              BUILD_DESKTOP=no COMPRESS_OUTPUTIMAGE=img
          sudo chown $(id -u):$(id -g) -R output/

      - name: Setup AmlImg & img2simg
        run: |
          sudo apt update && sudo apt install -y img2simg
          ver="v0.3.1"
          curl -L -o ./AmlImg https://github.com/hzyitc/AmlImg/releases/download/$ver/AmlImg_${ver}_linux_amd64
          chmod +x ./AmlImg

      - name: Process & Rename Images
        run: |
          DATE_STR=$(date +%Y%m%d)
          # 1. 下载并解压 U-Boot
          curl -L -o ./uboot.img https://github.com/${UBOOT_REPO}/releases/download/${UBOOT_TAG}/${UBOOT_BURNIMG}
          ./AmlImg unpack ./uboot.img burn/
          
          # 2. 处理生成的镜像
          diskimg=$(ls output/images/*.img)
          loop=$(sudo losetup --find --show --partscan $diskimg)
          sudo img2simg ${loop}p1 burn/boot.simg
          sudo img2simg ${loop}p2 burn/rootfs.simg
          sudo losetup -d $loop
          sudo chown $(id -u):$(id -g) -R burn/
          
          # 3. 生成线刷包验证文件
          echo -n "sha1sum $(sha1sum burn/boot.simg | awk '{print $1}')" >burn/boot.VERIFY
          echo -n "sha1sum $(sha1sum burn/rootfs.simg | awk '{print $1}')" >burn/rootfs.VERIFY
          cat <<EOF >>burn/commands.txt
          PARTITION:boot:sparse:boot.simg
          VERIFY:boot:normal:boot.VERIFY
          PARTITION:rootfs:sparse:rootfs.simg
          VERIFY:rootfs:normal:rootfs.VERIFY
          EOF
          
          # 4. 重命名并打包
          BASE_NAME="Armbian_Onecloud_${DATE_STR}_${{ matrix.RELEASE }}_${{ matrix.TYPE }}"
          ./AmlImg pack output/images/${BASE_NAME}.burn.img burn/
          mv $diskimg output/images/${BASE_NAME}.img

      - name: Compress & Hash
        run: |
          cd output/images/
          for f in *.img; do
            sha256sum "$f" >> ../../sha256sum_list
            xz -9 --threads=0 "$f"
          done

      - name: Update Release Body
        run: |
          echo "### SHA256 Checksum" > Release_Info.md
          cat sha256sum_list | awk '{printf "- %s: `%s`\n", $2, $1}' >> Release_Info.md

      - name: Upload to Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          append_body: true
          body_path: Release_Info.md
          files: output/images/*.xz
