name: one

on:
  workflow_dispatch:
  push:
    branches:
      - readme
    paths:
      - .github/workflows/one.yml

env:
  SCRIPT_REPO: ${{ github.repository }}
  SCRIPT_REF: ${{ github.ref_name }}
  UBOOT_REPO: qxar86/onecloud-u-boot
  UBOOT_RELEASE: latest
  UBOOT_BURNIMG: eMMC.burn.img
  ARMBIAN_REPO: armbian/build
  ARMBIAN_REF: main
  PATCHES: 4077,5076
  PATCHES_DISABLED: 5082

permissions:
  contents: write

jobs:
  prepare:
    name: Prepare
    runs-on: ubuntu-22.04
    outputs:
      env: ${{ steps.get.outputs.env }}
    steps:
      - id: get
        name: Get repositories information
        run: |
          TIME="$(curl -s https://api.github.com/repos/${SCRIPT_REPO}/actions/runs/${GITHUB_RUN_ID} | jq -r .created_at)"
          TAG="ci-$(date -d "${TIME}" -u +'%Y%m%d-%H%M%S-%Z')"
          SCRIPT_SHA=$(curl -s https://api.github.com/repos/${SCRIPT_REPO}/commits/${SCRIPT_REF} | jq -r .sha)
          UBOOT_TAG=$(curl -s https://api.github.com/repos/${UBOOT_REPO}/releases/${UBOOT_RELEASE} | jq -r .tag_name)
          ARMBIAN_SHA=$(curl -s https://api.github.com/repos/${ARMBIAN_REPO}/commits/${ARMBIAN_REF} | jq -r .sha)

          cat <<EOF >>$GITHUB_ENV
          TIME=$TIME
          TAG=$TAG
          SCRIPT_SHA=$SCRIPT_SHA
          UBOOT_TAG=$UBOOT_TAG
          ARMBIAN_SHA=$ARMBIAN_SHA
          EOF
          echo "env=$(cat $GITHUB_ENV | base64 -w 0)" >>$GITHUB_OUTPUT

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: CI ${{ env.TAG }}
          body: |
            Build info:
            Armbian: ${{ env.ARMBIAN_SHA }}
            Patches: ${{ env.PATCHES }}

  build-debs:
    name: Build Kernel
    needs: prepare
    runs-on: ubuntu-22.04
    steps:
      - name: Import env
        run: echo "$(echo "${{ needs.prepare.outputs.env }}" | base64 -d)" >>$GITHUB_ENV

      - name: Checkout Armbian
        uses: actions/checkout@v4
        with:
          repository: ${{ env.ARMBIAN_REPO }}
          ref: ${{ env.ARMBIAN_SHA }}

      - name: Apply Patches
        if: ${{ env.PATCHES != '' }}
        shell: bash
        run: |
          echo "::group::Download Patches"
          for id in $(echo $PATCHES | tr ',' ' '); do
            echo "Downloading PR #$id..."
            curl -fsSL "https://github.com/armbian/build/pull/${id}.patch" -o "${id}.patch" || exit 1
          done
          echo "::endgroup::"

          for file in *.patch; do
            if [ -s "$file" ]; then
              echo "::group::Applying $file"
              patch --batch -p1 -N < "$file"
              echo "::endgroup::"
            fi
          done

      - name: Build Kernel
        run: |
          export GITHUB_ACTIONS=false
          sudo --preserve-env ./compile.sh kernel \
            ALLOW_ROOT=yes BOARD=onecloud BRANCH=current EXPERT=yes USE_CCACHE=no
          sudo chown $(id -u):$(id -g) -R output/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: debs-current
          path: output/debs/*

  build:
    name: Build Image (${{ matrix.RELEASE }}-${{ matrix.TYPE }})
    needs: [ prepare, build-debs ]
    runs-on: ubuntu-22.04
    strategy:
      fail-fast: false
      matrix:
        RELEASE: [jammy, noble, bookworm, trixie]
        TYPE: [minimal, cli]
    steps:
      - name: Import env
        run: echo "$(echo "${{ needs.prepare.outputs.env }}" | base64 -d)" >>$GITHUB_ENV

      - name: Checkout Armbian
        uses: actions/checkout@v4
        with:
          repository: ${{ env.ARMBIAN_REPO }}
          ref: ${{ env.ARMBIAN_SHA }}

      - name: Apply Patches
        if: ${{ env.PATCHES != '' }}
        shell: bash
        run: |
          for id in $(echo $PATCHES | tr ',' ' '); do
            curl -fsSL "https://github.com/armbian/build/pull/${id}.patch" -o "${id}.patch"
          done
          for file in *.patch; do
            [ -s "$file" ] && patch --batch -p1 -N < "$file"
          done

      - name: Download debs
        uses: actions/download-artifact@v4
        with:
          name: debs-current
          path: output/debs/

      - name: Build OS Image
        run: |
          export GITHUB_ACTIONS=false
          sudo --preserve-env ./compile.sh build \
            ALLOW_ROOT=yes BOARD=onecloud BRANCH=current RELEASE=${{ matrix.RELEASE }} \
            KERNEL_CONFIGURE=no BUILD_MINIMAL=${{ matrix.TYPE == 'minimal' && 'yes' || 'no' }} \
            BUILD_DESKTOP=no EXPERT=yes SKIP_EXTERNAL_TOOLCHAINS=yes USE_CCACHE=no COMPRESS_OUTPUTIMAGE=img
          sudo chown $(id -u):$(id -g) -R output/

      - name: Generate Burn Image
        run: |
          sudo apt update && sudo apt install img2simg -y
          curl -fsSL -o ./AmlImg https://github.com/hzyitc/AmlImg/releases/download/v0.3.1/AmlImg_v0.3.1_linux_amd64
          chmod +x ./AmlImg
          curl -fsSL -o ./uboot.img https://github.com/${UBOOT_REPO}/releases/download/${UBOOT_TAG}/${UBOOT_BURNIMG}
          ./AmlImg unpack ./uboot.img burn/
          diskimg=$(ls output/images/*.img)
          loop=$(sudo losetup --find --show --partscan $diskimg)
          sudo img2simg ${loop}p1 burn/boot.simg
          sudo img2simg ${loop}p2 burn/rootfs.simg
          sudo losetup -d $loop
          ./AmlImg pack ${diskimg%.img}.burn.img burn/
          xz -T0 output/images/*.img

      - name: Upload to release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          files: |
            output/images/*.burn.img
            output/images/*.xz
